
homeassistant:
  country: IT
  customize: !include configurations/general/customize.yaml
  time_zone: !secret timezone
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric 
  packages: !include_dir_named configurations/packages/
frontend:
  themes: !include configurations/style/themes.yaml 
  extra_module_url:
    - www/community/lovelace-card-mod/card-mod.js 


#----------------------------------#
#discovery:
#----------------------------------#
lovelace: 
  mode: yaml
  resources: !include configurations/general/resources.yaml
#---------------------------------------------------------------#
automation: !include configurations/general/automations.yaml
script: !include configurations/general/scripts.yaml
sensor: !include configurations/general/sensors.yaml
light: !include configurations/general/lights.yaml
group: !include configurations/general/groups.yaml
cover: !include configurations/general/tapparelle.yaml
media_player: !include configurations/general/media_players.yaml
template: !include configurations/general/templates.yaml
#----------------------------------------------------------------#
mqtt: !include configurations/general/mqtt.yaml 

#------------RECORDER--------------#
recorder: !include configurations/general/recorder.yaml  
#influxdb: !include www/configurations/influxdb.yaml

#----------------------------------#
logger:
  default: info
  logs:
    homeassistant.components.vacuum: debug
#----------------------------------#

spotcast: 
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key

tts:
  - platform: google_translate
#----------------------------------#

#----------------------------------#
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
#----------------------------------#
input_boolean:
  home_theatre_switch:
    name: Accendi l'impianto home theatre
    #initial: off
    icon: mdi:movie-open
#----------------------------------#security
#camera:
#  - platform: foscam
#    ip: !secret ip_webcam
#    rtsp_port: 88
#    username: !secret foscam_user
#    password: !secret foscam_password



input_text:
  room_cleaning:
    name: Currently Cleaning Room
    initial: charging
  frase_ambrogio:
    name: Frase popup ambrogio
 
    
  #https://www.home-assistant.io/components/sensor.command_line/
#command_line:
#  - sensor: 
#      name: CPU Temperature
#      command: "cat /sys/class/thermal/thermal_zone0/temp"
#      unit_of_measurement: "°C"
#      value_template: '{{ value | multiply(0.001) | round(1) }}'

