
#- alias: 'Accendi_Tutto'
#  trigger:
#    platform: state
#    entity_id: input_boolean.home_theatre_switch
#    to: 'on'
#  action:
#    - service: media_player.turn_on
#      entity_id: 
#        - media_player.amplificatore
#    - service: media_player.turn_on
#      entity_id: 
#        - media_player.epson_projector
#    - service: light.turn_on
#      entity_id: 
#        - group.torri
#        - light.cielo_rgb_light
#    - service: light.turn_off
#      entity_id: light.luce_della_scala
#
#    - service: androidtv.adb_command
#      data:
#        entity_id: media_player.nvidiashield
#        command: "POWER"


#- alias: 'Spegni_Tutto'
#  trigger:
#    platform: state
#    entity_id: input_boolean.home_theatre_switch
#    to: 'off'
#  action:
#    - service: media_player.turn_off
#      entity_id: 
#        - media_player.amplificatore
#    - service: media_player.turn_off
#      entity_id: 
#        - media_player.epson_projector        
#    - service: light.turn_off
#      entity_id: 
#        - group.torri
#       - light.cielo_rgb_light
#
#    - service: light.turn_on
#      entity_id: light.luce_della_scala
#
#    - service: androidtv.adb_command
#      data:
#        entity_id: media_player.nvidiashield
#        command: "SLEEP"


- alias: 'luci_taverna_on'
  trigger:
    platform: event
    event_type: luci_taverna_on
  action:
    - service: light.turn_on
      entity_id: 
        - group.torri
        - light.cielo_rgb_light


- alias: 'luci_taverna_off'
  trigger:
    platform: event
    event_type: luci_taverna_off
  action:
    - service: light.turn_off
      entity_id: 
        - group.torri
        - light.cielo_rgb_light

    
- alias: 'Luci cinema'
  trigger:
    platform: event
    event_type: luci_cinema
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.aeotec_limited_zwa002_led_bulb_6_multi_color_level
          - light.aeotec_limited_zwa002_led_bulb_6_multi_color_level_4
        rgb_color: [153, 0, 153]
        brightness: 255
    - service: light.turn_on
      data:
        entity_id:
          - light.aeotec_limited_zwa002_led_bulb_6_multi_color_level_2
          - light.aeotec_limited_zwa002_led_bulb_6_multi_color_level_3
        rgb_color: [255, 51, 0]
        brightness: 255


- alias: 'Play/resume mode'
  trigger:
    platform: webhook
    webhook_id: play_resume
  action:
    - service: light.turn_off
      entity_id: 
       - group.torri
       - light.cielo_rgb_light

    
- alias: 'Stop/pausa mode'
  trigger:
    platform: webhook
    webhook_id: stop_pausa
  action:
    - service: light.turn_on
      entity_id: 
       - group.torri
       - light.cielo_rgb_light



- alias: 'Playing mode Netflix/Primevideo'
  trigger:
    - platform: state
      entity_id: media_player.nvidiashield
      to: 'playing'
  condition:
    - condition: and
      conditions:
#        - condition: state
#          entity_id: 'light.cielo_rgb_light'
#          state: 'on'
#        - condition: state
#          entity_id: 'group.torri'
#          state: 'on'
        - condition: or
          conditions:
          - condition: template
            value_template: "{{ state_attr('media_player.nvidiashield', 'app_id') == 'com.netflix.ninja'}}"
          - condition: template
            value_template: "{{ state_attr('media_player.nvidiashield', 'app_id') == 'com.amazon.amazonvideo.livingroom'}}"
  action:
    - service: light.turn_off
      entity_id:
        - group.torri
        - light.cielo_rgb_light
 
 
 
        
- alias: 'Pause/Idle mode Netflix/Primevideo'
  trigger:
    - platform: state
      entity_id: media_player.nvidiashield
      to: 'idle'
    - platform: state
      entity_id: media_player.nvidiashield
      to: 'paused'
  condition:
    - condition: and
      conditions:
#        - condition: state
#          entity_id: 'light.cielo_rgb_light'
#          state: 'off'
#        - condition: state
#          entity_id: 'group.torri'
#          state: 'off'            
        - condition: or
          conditions:
            - condition: template
              value_template: "{{ state_attr('media_player.nvidiashield', 'app_id') == 'com.netflix.ninja'}}"
            - condition: template
              value_template: "{{ state_attr('media_player.nvidiashield', 'app_id') == 'com.amazon.amazonvideo.livingroom'}}"
  action:
    - service: light.turn_on
      entity_id:
        - group.torri
        - light.cielo_rgb_light
     
- alias: 'IFTTT-HA'
  trigger:
    - platform: event
      event_type: ifttt_webhook_received
      event_data:
        action: 'call_service'
  action:
    - service: '{{ trigger.event.data.service }}'
      data_template:
        entity_id: '{{ trigger.event.data.entity_id }}'


 
############# FIX PER MANCATO REPORT COLORE LUCI AEOTEC #################

#- alias: 'aggiorna_colore_luce_1'
#  trigger:
#    - platform: state
#      entity_id: light.aeotec_limited_zwa002_led_bulb_6_multi_color_level
#  condition:
#    - condition: template
#      value_template: '{{ as_timestamp(now()) - as_timestamp(states.script.aggiorna_colore_luce_1.attributes.last_triggered) | int > 9 }}'  
#  action:
#    - service: script.turn_off
#      entity_id: script.aggiorna_colore_luce_1
#    - service: script.aggiorna_colore_luce_1


#- alias: 'aggiorna_colore_ luce_2'
#  trigger:
#    - platform: state
#      entity_id: light.aeotec_limited_zwa002_led_bulb_6_multi_color_level_2
#
#  condition:
#    - condition: template
#      value_template: '{{ as_timestamp(now()) - as_timestamp(states.script.aggiorna_colore_luce_2.attributes.last_triggered) | int > 10 }}'  
#  action:
#    - service: script.turn_off
#      entity_id: script.aggiorna_colore_luce_2
#    - service: script.aggiorna_colore_luce_2


#- alias: 'aggiorna_colore_luce_3'
#  trigger:
#    - platform: state
#      entity_id: light.aeotec_limited_zwa002_led_bulb_6_multi_color_level_3
#
#  condition:
#    - condition: template
#      value_template: '{{ as_timestamp(now()) - as_timestamp(states.script.aggiorna_colore_luce_3.attributes.last_triggered) | int > 11 }}'  
#  action:
#    - service: script.turn_off
#      entity_id: script.aggiorna_colore_luce_3
#    - service: script.aggiorna_colore_luce_3


#- alias: 'aggiorna_colore_luce_4'
#  trigger:
#    - platform: state
#      entity_id: light.aeotec_limited_zwa002_led_bulb_6_multi_color_level_4
#
#  condition:
#    - condition: template
#      value_template: '{{ as_timestamp(now()) - as_timestamp(states.script.aggiorna_colore_luce_4.attributes.last_triggered) | int > 12 }}'  
#  action:
#    - service: script.turn_off
#      entity_id: script.aggiorna_colore_luce_4
#    - service: script.aggiorna_colore_luce_4

############### FIX FIBARO ROLLER   #############

- alias: 'aggiorna_posizione_cover_soggiorno'
  trigger:
  - platform: state
    entity_id: sensor.posizione_tapparella_soggiorno
    to: '0.0'
  action:
    - service: zwave.refresh_entity
      data_template:
        entity_id: 'cover.fibaro_system_fgrm223_roller_shutter_controller_3_level'


- alias: 'aggiorna_posizione_cover_studio'
  trigger:
  - platform: state
    entity_id: sensor.posizione_tapparella_studio
    to: '0.0'
  action:
    - service: zwave.refresh_entity
      data_template:
        entity_id: 'cover.fibaro_system_fgrm223_roller_shutter_controller_3_level_2'


- alias: 'aggiorna_posizione_cover_camera'
  trigger:
  - platform: state
    entity_id: sensor.posizione_tapparella_camera
    to: '0.0'
  action:
    - service: zwave.refresh_entity
      data_template:
        entity_id: 'cover.fibaro_system_fgrm223_roller_shutter_controller_3_level_3'



#- alias: 'Trigger popup frase ambrogio'
#  trigger:
#    - platform: state
#      entity_id: input_text.room_cleaning
#      to: 'xxxxx'
#  action:

  
